name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "docker.zhpjy.top"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.zhpjy.top", custom_domain = true },
  { pattern = "quay.docker.zhpjy.top", custom_domain = true },
  { pattern = "gcr.docker.zhpjy.top", custom_domain = true },
  { pattern = "k8s-gcr.docker.zhpjy.top", custom_domain = true },
  { pattern = "k8s.docker.zhpjy.top", custom_domain = true },
  { pattern = "ghcr.docker.zhpjy.top", custom_domain = true },
  { pattern = "cloudsmith.docker.zhpjy.top", custom_domain = true },

  { pattern = "quay.io.docker.zhpjy.top", custom_domain = true },
  { pattern = "gcr.io.docker.zhpjy.top", custom_domain = true },
  { pattern = "k8s.gcr.io.docker.zhpjy.top", custom_domain = true },
  { pattern = "registry.k8s.io.docker.zhpjy.top", custom_domain = true },
  { pattern = "ghcr.io.docker.zhpjy.top", custom_domain = true },
  { pattern = "docker.cloudsmith.io.docker.zhpjy.top", custom_domain = true },
  { pattern = "public.ecr.aws.docker.zhpjy.top", custom_domain = true },
  { pattern = "lscr.io.docker.zhpjy.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "docker.zhpjy.top"

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.zhpjy.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.